name: "Post Article"

on:
  workflow_dispatch:
    inputs:
      title:
        description: "Article title (e.g. Who am I)"
        required: true
        type: string
      body:
        description: "HTML body – paste <p>...</p> etc. Use \\n for new lines."
        required: true
        type: string
      date:
        description: "Display date (optional, default = today)"
        required: false
        type: string
      readtime:
        description: "Reading time in minutes (optional, default = 2)"
        required: false
        type: string

permissions:
  contents: write   # allows the workflow to push to main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Insert article into index.html
        env:
          TITLE: ${{ inputs.title }}
          BODY: ${{ inputs.body }}
          DATE_IN: ${{ inputs.date }}
          READ_MIN: ${{ inputs.readtime }}
        run: |
          python <<'PY'
          import os, datetime, pathlib, re, sys
          title = os.getenv("TITLE")
          body  = os.getenv("BODY")
          date  = os.getenv("DATE_IN") or datetime.date.today().strftime("%d %B %Y")
          read  = os.getenv("READ_MIN") or "2"

          blk = f"""            <article>
                <h2>{title}</h2>
                <p class="meta">{date} · {read} min read</p>
{body}
            </article>\n"""

          idx = pathlib.Path("index.html")
          if not idx.exists():
              sys.exit("index.html not found")

          text = idx.read_text()
          m = re.search(r"</section>", text, flags=re.I)
          if not m:
              sys.exit("Could not locate </section> tag")
          text = text[:m.start()] + blk + text[m.start():]
          idx.write_text(text)
          PY

      - name: Commit & push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if git diff --quiet; then
            echo "No changes"; exit 0
          fi
          git add index.html
          git commit -m "chore: add article via workflow"
          git push
